#define GENERATED_DATA_SECTION(NAME) CUSHION_STATEMENT_ACCUMULATOR (section_ ## NAME)
#define GENERATED_DATA_BIND(NAME) CUSHION_STATEMENT_ACCUMULATOR_REF (bound_section, section_ ## NAME)
#define GENERATED_FIELD(NAME) int NAME;
#define GENERATED_DATA_FIELD(NAME) CUSHION_STATEMENT_ACCUMULATOR_PUSH (bound_section) { GENERATED_FIELD (NAME) }
#define GENERATED_DATA_FIELD_CUSTOM CUSHION_STATEMENT_ACCUMULATOR_PUSH (bound_section) { __CUSHION_WRAPPED__ }
#define GENERATED_DATA_UNBIND CUSHION_STATEMENT_ACCUMULATOR_UNREF (bound_section)

struct data_t
{
    GENERATED_DATA_SECTION (my_data)
    GENERATED_DATA_BIND (my_data)
};

GENERATED_DATA_FIELD (x)
GENERATED_DATA_FIELD (y)
GENERATED_DATA_FIELD (z)
GENERATED_DATA_FIELD (w)
GENERATED_DATA_FIELD_CUSTOM { float hello_world; }

GENERATED_DATA_UNBIND

int function (void)
{
    return 0;
}
